-- Seed common exercises (200 exercises with categories and muscle groups)
INSERT INTO exercises (name, category, primary_muscle_group, secondary_muscle_groups, equipment, difficulty_level, description, is_public) VALUES

-- CHEST EXERCISES (20)
('Barbell Bench Press', 'strength', 'chest', ARRAY['triceps', 'shoulders'], 'barbell', 'intermediate', 'Classic compound chest exercise', true),
('Dumbbell Bench Press', 'strength', 'chest', ARRAY['triceps', 'shoulders'], 'dumbbell', 'intermediate', 'Chest press with dumbbells for greater range of motion', true),
('Incline Barbell Bench Press', 'strength', 'chest', ARRAY['shoulders', 'triceps'], 'barbell', 'intermediate', 'Targets upper chest', true),
('Decline Barbell Bench Press', 'strength', 'chest', ARRAY['triceps'], 'barbell', 'intermediate', 'Targets lower chest', true),
('Push-ups', 'strength', 'chest', ARRAY['triceps', 'shoulders', 'core'], 'bodyweight', 'beginner', 'Basic bodyweight chest exercise', true),
('Dumbbell Flyes', 'strength', 'chest', ARRAY['shoulders'], 'dumbbell', 'intermediate', 'Isolation exercise for chest', true),
('Cable Crossover', 'strength', 'chest', ARRAY['shoulders'], 'cable', 'intermediate', 'Cable chest isolation', true),
('Chest Dips', 'strength', 'chest', ARRAY['triceps', 'shoulders'], 'bodyweight', 'intermediate', 'Bodyweight chest and tricep exercise', true),
('Incline Dumbbell Press', 'strength', 'chest', ARRAY['shoulders', 'triceps'], 'dumbbell', 'intermediate', 'Upper chest focus with dumbbells', true),
('Pec Deck Machine', 'strength', 'chest', NULL, 'machine', 'beginner', 'Chest fly machine', true),
('Landmine Press', 'strength', 'chest', ARRAY['shoulders', 'triceps'], 'barbell', 'intermediate', 'Angled chest press', true),
('Svend Press', 'strength', 'chest', ARRAY['shoulders'], 'plate', 'beginner', 'Plate squeeze press', true),
('Floor Press', 'strength', 'chest', ARRAY['triceps'], 'barbell', 'intermediate', 'Bench press from floor', true),
('Resistance Band Chest Press', 'strength', 'chest', ARRAY['shoulders', 'triceps'], 'resistance_band', 'beginner', 'Chest press with bands', true),
('Diamond Push-ups', 'strength', 'chest', ARRAY['triceps'], 'bodyweight', 'intermediate', 'Close-grip push-up variation', true),
('Wide-Grip Push-ups', 'strength', 'chest', ARRAY['shoulders'], 'bodyweight', 'beginner', 'Push-ups with wide hand placement', true),
('Decline Push-ups', 'strength', 'chest', ARRAY['shoulders', 'triceps'], 'bodyweight', 'intermediate', 'Feet elevated push-ups', true),
('Cable Chest Press', 'strength', 'chest', ARRAY['shoulders', 'triceps'], 'cable', 'beginner', 'Standing cable press', true),
('Machine Chest Press', 'strength', 'chest', ARRAY['shoulders', 'triceps'], 'machine', 'beginner', 'Seated chest press machine', true),
('Plyometric Push-ups', 'strength', 'chest', ARRAY['triceps', 'shoulders'], 'bodyweight', 'advanced', 'Explosive push-ups', true),

-- BACK EXERCISES (25)
('Deadlift', 'strength', 'back', ARRAY['glutes', 'hamstrings', 'core'], 'barbell', 'advanced', 'King of back exercises', true),
('Pull-ups', 'strength', 'back', ARRAY['biceps', 'shoulders'], 'bodyweight', 'intermediate', 'Classic bodyweight back exercise', true),
('Barbell Row', 'strength', 'back', ARRAY['biceps', 'shoulders'], 'barbell', 'intermediate', 'Bent-over row', true),
('Lat Pulldown', 'strength', 'back', ARRAY['biceps'], 'cable', 'beginner', 'Cable lat exercise', true),
('T-Bar Row', 'strength', 'back', ARRAY['biceps', 'shoulders'], 'barbell', 'intermediate', 'Landmine row variation', true),
('Seated Cable Row', 'strength', 'back', ARRAY['biceps', 'shoulders'], 'cable', 'beginner', 'Seated rowing machine', true),
('One-Arm Dumbbell Row', 'strength', 'back', ARRAY['biceps'], 'dumbbell', 'intermediate', 'Unilateral back exercise', true),
('Chin-ups', 'strength', 'back', ARRAY['biceps'], 'bodyweight', 'intermediate', 'Underhand grip pull-ups', true),
('Face Pulls', 'strength', 'back', ARRAY['shoulders'], 'cable', 'beginner', 'Rear delt and upper back', true),
('Hyperextensions', 'strength', 'back', ARRAY['glutes', 'hamstrings'], 'bodyweight', 'beginner', 'Lower back extension', true),
('Inverted Rows', 'strength', 'back', ARRAY['biceps'], 'bodyweight', 'intermediate', 'Horizontal pull', true),
('Dumbbell Pullover', 'strength', 'back', ARRAY['chest'], 'dumbbell', 'intermediate', 'Lat stretch and contraction', true),
('Romanian Deadlift', 'strength', 'back', ARRAY['hamstrings', 'glutes'], 'barbell', 'intermediate', 'Hip hinge deadlift variation', true),
('Sumo Deadlift', 'strength', 'back', ARRAY['glutes', 'quads', 'adductors'], 'barbell', 'advanced', 'Wide stance deadlift', true),
('Good Mornings', 'strength', 'back', ARRAY['hamstrings', 'glutes'], 'barbell', 'intermediate', 'Hip hinge exercise', true),
('Rack Pulls', 'strength', 'back', ARRAY['traps'], 'barbell', 'intermediate', 'Partial deadlift from rack', true),
('Pendlay Row', 'strength', 'back', ARRAY['biceps'], 'barbell', 'advanced', 'Strict barbell row from floor', true),
('Meadows Row', 'strength', 'back', ARRAY['biceps'], 'barbell', 'advanced', 'One-arm landmine row', true),
('Chest-Supported Row', 'strength', 'back', ARRAY['biceps'], 'dumbbell', 'beginner', 'Incline bench row', true),
('Single-Arm Cable Row', 'strength', 'back', ARRAY['biceps'], 'cable', 'beginner', 'Unilateral cable row', true),
('Wide-Grip Pull-ups', 'strength', 'back', ARRAY['biceps'], 'bodyweight', 'intermediate', 'Wide grip variation', true),
('Neutral Grip Pull-ups', 'strength', 'back', ARRAY['biceps'], 'bodyweight', 'intermediate', 'Parallel grip pull-ups', true),
('Assisted Pull-ups', 'strength', 'back', ARRAY['biceps'], 'machine', 'beginner', 'Pull-ups with assistance', true),
('Straight-Arm Pulldown', 'strength', 'back', NULL, 'cable', 'intermediate', 'Lat isolation', true),
('Seal Row', 'strength', 'back', ARRAY['biceps'], 'barbell', 'intermediate', 'Prone barbell row', true),

-- SHOULDER EXERCISES (20)
('Overhead Press', 'strength', 'shoulders', ARRAY['triceps', 'core'], 'barbell', 'intermediate', 'Standing shoulder press', true),
('Dumbbell Shoulder Press', 'strength', 'shoulders', ARRAY['triceps'], 'dumbbell', 'intermediate', 'Seated or standing DB press', true),
('Lateral Raises', 'strength', 'shoulders', NULL, 'dumbbell', 'beginner', 'Side deltoid isolation', true),
('Front Raises', 'strength', 'shoulders', NULL, 'dumbbell', 'beginner', 'Front deltoid isolation', true),
('Rear Delt Flyes', 'strength', 'shoulders', NULL, 'dumbbell', 'beginner', 'Rear deltoid isolation', true),
('Arnold Press', 'strength', 'shoulders', ARRAY['triceps'], 'dumbbell', 'intermediate', 'Rotating dumbbell press', true),
('Military Press', 'strength', 'shoulders', ARRAY['triceps', 'core'], 'barbell', 'intermediate', 'Strict overhead press', true),
('Push Press', 'strength', 'shoulders', ARRAY['legs', 'core'], 'barbell', 'advanced', 'Explosive overhead press', true),
('Bradford Press', 'strength', 'shoulders', ARRAY['triceps'], 'barbell', 'intermediate', 'Behind neck to front press', true),
('Cable Lateral Raises', 'strength', 'shoulders', NULL, 'cable', 'beginner', 'Cable side delt raises', true),
('Upright Row', 'strength', 'shoulders', ARRAY['traps'], 'barbell', 'intermediate', 'Vertical pulling motion', true),
('Landmine Press', 'strength', 'shoulders', ARRAY['core'], 'barbell', 'intermediate', 'Angled overhead press', true),
('Viking Press', 'strength', 'shoulders', ARRAY['triceps'], 'barbell', 'intermediate', 'Neutral grip landmine press', true),
('Dumbbell Clean and Press', 'strength', 'shoulders', ARRAY['legs', 'back'], 'dumbbell', 'advanced', 'Full body power movement', true),
('Pike Push-ups', 'strength', 'shoulders', ARRAY['triceps'], 'bodyweight', 'intermediate', 'Bodyweight shoulder press', true),
('Handstand Push-ups', 'strength', 'shoulders', ARRAY['triceps', 'core'], 'bodyweight', 'advanced', 'Vertical push-up', true),
('Face Pulls', 'strength', 'shoulders', ARRAY['back'], 'cable', 'beginner', 'Rear delt and upper back', true),
('Band Pull-Aparts', 'strength', 'shoulders', ARRAY['back'], 'resistance_band', 'beginner', 'Rear delt activation', true),
('Shrugs', 'strength', 'shoulders', ARRAY['traps'], 'dumbbell', 'beginner', 'Trap isolation', true),
('Barbell Shrugs', 'strength', 'shoulders', ARRAY['traps'], 'barbell', 'beginner', 'Heavy trap work', true),

-- ARM EXERCISES - BICEPS (15)
('Barbell Curl', 'strength', 'biceps', NULL, 'barbell', 'beginner', 'Classic bicep curl', true),
('Dumbbell Curl', 'strength', 'biceps', NULL, 'dumbbell', 'beginner', 'Alternating or simultaneous curls', true),
('Hammer Curl', 'strength', 'biceps', ARRAY['forearms'], 'dumbbell', 'beginner', 'Neutral grip curl', true),
('Preacher Curl', 'strength', 'biceps', NULL, 'barbell', 'intermediate', 'Isolated bicep curl', true),
('Concentration Curl', 'strength', 'biceps', NULL, 'dumbbell', 'beginner', 'Single-arm isolation', true),
('Cable Curl', 'strength', 'biceps', NULL, 'cable', 'beginner', 'Constant tension curls', true),
('Incline Dumbbell Curl', 'strength', 'biceps', NULL, 'dumbbell', 'intermediate', 'Stretched position curl', true),
('Spider Curl', 'strength', 'biceps', NULL, 'barbell', 'intermediate', 'Incline bench curl', true),
('21s Curl', 'strength', 'biceps', NULL, 'barbell', 'intermediate', '7 bottom, 7 top, 7 full reps', true),
('Reverse Curl', 'strength', 'biceps', ARRAY['forearms'], 'barbell', 'intermediate', 'Overhand grip curl', true),
('Zottman Curl', 'strength', 'biceps', ARRAY['forearms'], 'dumbbell', 'intermediate', 'Rotating curl', true),
('Drag Curl', 'strength', 'biceps', NULL, 'barbell', 'intermediate', 'Barbell dragged along body', true),
('Cross-Body Hammer Curl', 'strength', 'biceps', ARRAY['forearms'], 'dumbbell', 'beginner', 'Hammer curl across body', true),
('EZ-Bar Curl', 'strength', 'biceps', NULL, 'barbell', 'beginner', 'Angled bar curl', true),
('Bayesian Curl', 'strength', 'biceps', NULL, 'cable', 'intermediate', 'Cable curl with stretched position', true),

-- ARM EXERCISES - TRICEPS (15)
('Tricep Dips', 'strength', 'triceps', ARRAY['chest', 'shoulders'], 'bodyweight', 'intermediate', 'Parallel bar dips', true),
('Close-Grip Bench Press', 'strength', 'triceps', ARRAY['chest'], 'barbell', 'intermediate', 'Narrow grip press', true),
('Tricep Pushdown', 'strength', 'triceps', NULL, 'cable', 'beginner', 'Cable tricep extension', true),
('Overhead Tricep Extension', 'strength', 'triceps', NULL, 'dumbbell', 'beginner', 'Overhead DB extension', true),
('Skull Crushers', 'strength', 'triceps', NULL, 'barbell', 'intermediate', 'Lying tricep extension', true),
('Diamond Push-ups', 'strength', 'triceps', ARRAY['chest'], 'bodyweight', 'intermediate', 'Close-grip push-ups', true),
('Rope Pushdown', 'strength', 'triceps', NULL, 'cable', 'beginner', 'Rope attachment pushdown', true),
('Kickbacks', 'strength', 'triceps', NULL, 'dumbbell', 'beginner', 'Bent-over tricep extension', true),
('JM Press', 'strength', 'triceps', NULL, 'barbell', 'advanced', 'Hybrid press/extension', true),
('Tate Press', 'strength', 'triceps', NULL, 'dumbbell', 'intermediate', 'Elbows-out extension', true),
('Single-Arm Cable Extension', 'strength', 'triceps', NULL, 'cable', 'beginner', 'Unilateral cable work', true),
('French Press', 'strength', 'triceps', NULL, 'barbell', 'intermediate', 'Lying overhead extension', true),
('Bench Dips', 'strength', 'triceps', NULL, 'bodyweight', 'beginner', 'Bench-supported dips', true),
('Cable Overhead Extension', 'strength', 'triceps', NULL, 'cable', 'beginner', 'Overhead cable extension', true),
('Close-Grip Push-ups', 'strength', 'triceps', ARRAY['chest'], 'bodyweight', 'beginner', 'Narrow hand placement', true),

-- LEG EXERCISES - QUADS (15)
('Barbell Squat', 'strength', 'quads', ARRAY['glutes', 'hamstrings', 'core'], 'barbell', 'intermediate', 'King of leg exercises', true),
('Front Squat', 'strength', 'quads', ARRAY['core'], 'barbell', 'advanced', 'Front-loaded squat', true),
('Leg Press', 'strength', 'quads', ARRAY['glutes', 'hamstrings'], 'machine', 'beginner', 'Machine leg press', true),
('Bulgarian Split Squat', 'strength', 'quads', ARRAY['glutes'], 'dumbbell', 'intermediate', 'Rear-foot elevated split squat', true),
('Leg Extension', 'strength', 'quads', NULL, 'machine', 'beginner', 'Quad isolation', true),
('Goblet Squat', 'strength', 'quads', ARRAY['glutes', 'core'], 'dumbbell', 'beginner', 'Front-loaded squat with DB', true),
('Hack Squat', 'strength', 'quads', ARRAY['glutes'], 'machine', 'intermediate', 'Machine hack squat', true),
('Walking Lunges', 'strength', 'quads', ARRAY['glutes', 'hamstrings'], 'dumbbell', 'beginner', 'Forward lunges', true),
('Step-ups', 'strength', 'quads', ARRAY['glutes'], 'dumbbell', 'beginner', 'Box or bench step-ups', true),
('Sissy Squat', 'strength', 'quads', NULL, 'bodyweight', 'advanced', 'Quad isolation squat', true),
('Box Squat', 'strength', 'quads', ARRAY['glutes', 'hamstrings'], 'barbell', 'intermediate', 'Squat to box', true),
('Pistol Squat', 'strength', 'quads', ARRAY['glutes', 'core'], 'bodyweight', 'advanced', 'Single-leg squat', true),
('Zercher Squat', 'strength', 'quads', ARRAY['core', 'back'], 'barbell', 'advanced', 'Barbell in elbow crease', true),
('Safety Bar Squat', 'strength', 'quads', ARRAY['glutes', 'hamstrings'], 'barbell', 'intermediate', 'Special bar squat', true),
('Cyclist Squat', 'strength', 'quads', NULL, 'barbell', 'advanced', 'Heels elevated squat', true),

-- LEG EXERCISES - HAMSTRINGS & GLUTES (15)
('Romanian Deadlift', 'strength', 'hamstrings', ARRAY['glutes', 'back'], 'barbell', 'intermediate', 'Hip hinge movement', true),
('Leg Curl', 'strength', 'hamstrings', NULL, 'machine', 'beginner', 'Hamstring isolation', true),
('Good Mornings', 'strength', 'hamstrings', ARRAY['back', 'glutes'], 'barbell', 'intermediate', 'Hip hinge with barbell', true),
('Hip Thrust', 'strength', 'glutes', ARRAY['hamstrings'], 'barbell', 'intermediate', 'Glute bridge with barbell', true),
('Glute Bridge', 'strength', 'glutes', ARRAY['hamstrings'], 'bodyweight', 'beginner', 'Bodyweight hip thrust', true),
('Nordic Hamstring Curl', 'strength', 'hamstrings', NULL, 'bodyweight', 'advanced', 'Eccentric hamstring work', true),
('Cable Pull-Through', 'strength', 'glutes', ARRAY['hamstrings'], 'cable', 'beginner', 'Hip hinge with cable', true),
('Single-Leg Deadlift', 'strength', 'hamstrings', ARRAY['glutes', 'core'], 'dumbbell', 'intermediate', 'Unilateral RDL', true),
('Glute Ham Raise', 'strength', 'hamstrings', ARRAY['glutes'], 'machine', 'advanced', 'GHD exercise', true),
('Kettlebell Swing', 'strength', 'glutes', ARRAY['hamstrings', 'back'], 'kettlebell', 'intermediate', 'Explosive hip hinge', true),
('Sumo Deadlift', 'strength', 'glutes', ARRAY['quads', 'hamstrings'], 'barbell', 'advanced', 'Wide stance deadlift', true),
('Reverse Hyper', 'strength', 'glutes', ARRAY['hamstrings', 'back'], 'machine', 'intermediate', 'Reverse hyperextension', true),
('B-Stance Hip Thrust', 'strength', 'glutes', ARRAY['hamstrings'], 'barbell', 'intermediate', 'Kickstand hip thrust', true),
('Donkey Kick', 'strength', 'glutes', NULL, 'bodyweight', 'beginner', 'Quadruped hip extension', true),
('Fire Hydrant', 'strength', 'glutes', NULL, 'bodyweight', 'beginner', 'Hip abduction exercise', true),

-- CALVES (5)
('Standing Calf Raise', 'strength', 'calves', NULL, 'machine', 'beginner', 'Standing calf exercise', true),
('Seated Calf Raise', 'strength', 'calves', NULL, 'machine', 'beginner', 'Seated calf isolation', true),
('Donkey Calf Raise', 'strength', 'calves', NULL, 'machine', 'intermediate', 'Bent-over calf raise', true),
('Single-Leg Calf Raise', 'strength', 'calves', NULL, 'bodyweight', 'beginner', 'Unilateral calf work', true),
('Jump Rope', 'cardio', 'calves', ARRAY['cardio'], 'jump_rope', 'beginner', 'Cardio with calf work', true),

-- CORE/ABS (20)
('Plank', 'strength', 'core', NULL, 'bodyweight', 'beginner', 'Isometric core hold', true),
('Crunches', 'strength', 'core', NULL, 'bodyweight', 'beginner', 'Basic ab exercise', true),
('Russian Twists', 'strength', 'core', NULL, 'bodyweight', 'beginner', 'Rotational core work', true),
('Leg Raises', 'strength', 'core', NULL, 'bodyweight', 'intermediate', 'Lower ab exercise', true),
('Bicycle Crunches', 'strength', 'core', NULL, 'bodyweight', 'beginner', 'Dynamic ab exercise', true),
('Side Plank', 'strength', 'core', NULL, 'bodyweight', 'beginner', 'Lateral core stability', true),
('Mountain Climbers', 'cardio', 'core', NULL, 'bodyweight', 'beginner', 'Dynamic core and cardio', true),
('Ab Wheel Rollout', 'strength', 'core', NULL, 'ab_wheel', 'advanced', 'Advanced core extension', true),
('Hanging Leg Raises', 'strength', 'core', NULL, 'bodyweight', 'advanced', 'Hanging ab exercise', true),
('Dead Bug', 'strength', 'core', NULL, 'bodyweight', 'beginner', 'Core stability exercise', true),
('Bird Dog', 'strength', 'core', ARRAY['back'], 'bodyweight', 'beginner', 'Core and back stability', true),
('Pallof Press', 'strength', 'core', NULL, 'cable', 'intermediate', 'Anti-rotation exercise', true),
('Cable Woodchop', 'strength', 'core', NULL, 'cable', 'intermediate', 'Rotational cable exercise', true),
('Decline Sit-ups', 'strength', 'core', NULL, 'bodyweight', 'intermediate', 'Weighted sit-up variation', true),
('V-Ups', 'strength', 'core', NULL, 'bodyweight', 'intermediate', 'Full body crunch', true),
('Hollow Hold', 'strength', 'core', NULL, 'bodyweight', 'intermediate', 'Isometric ab hold', true),
('Dragon Flag', 'strength', 'core', NULL, 'bodyweight', 'advanced', 'Advanced core exercise', true),
('L-Sit', 'strength', 'core', NULL, 'bodyweight', 'advanced', 'Isometric hold', true),
('Windshield Wipers', 'strength', 'core', NULL, 'bodyweight', 'advanced', 'Hanging rotational exercise', true),
('Turkish Get-Up', 'strength', 'core', ARRAY['shoulders', 'stability'], 'kettlebell', 'advanced', 'Full body movement', true),

-- CARDIO (15)
('Running', 'cardio', 'cardio', NULL, 'none', 'beginner', 'Outdoor or treadmill running', true),
('Cycling', 'cardio', 'cardio', NULL, 'bike', 'beginner', 'Stationary or outdoor cycling', true),
('Rowing', 'cardio', 'cardio', ARRAY['back', 'legs'], 'rowing_machine', 'beginner', 'Full body cardio', true),
('Swimming', 'cardio', 'cardio', NULL, 'none', 'beginner', 'Low-impact full body cardio', true),
('Elliptical', 'cardio', 'cardio', NULL, 'elliptical', 'beginner', 'Low-impact cardio machine', true),
('Stair Climber', 'cardio', 'cardio', ARRAY['glutes', 'quads'], 'machine', 'beginner', 'Stair climbing machine', true),
('Battle Ropes', 'cardio', 'cardio', ARRAY['shoulders', 'core'], 'battle_ropes', 'intermediate', 'High-intensity rope exercise', true),
('Box Jumps', 'cardio', 'cardio', ARRAY['quads', 'glutes'], 'box', 'intermediate', 'Plyometric box exercise', true),
('Burpees', 'cardio', 'cardio', ARRAY['chest', 'core'], 'bodyweight', 'intermediate', 'Full body conditioning', true),
('Jumping Jacks', 'cardio', 'cardio', NULL, 'bodyweight', 'beginner', 'Basic cardio exercise', true),
('High Knees', 'cardio', 'cardio', NULL, 'bodyweight', 'beginner', 'Running in place', true),
('Jump Rope', 'cardio', 'cardio', ARRAY['calves'], 'jump_rope', 'beginner', 'Cardio with coordination', true),
('Sprints', 'cardio', 'cardio', NULL, 'none', 'intermediate', 'High-intensity running', true),
('Sled Push', 'cardio', 'cardio', ARRAY['quads', 'glutes'], 'sled', 'intermediate', 'Pushing weighted sled', true),
('Sled Pull', 'cardio', 'cardio', ARRAY['back', 'hamstrings'], 'sled', 'intermediate', 'Pulling weighted sled', true);
